# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "parallels" do |v, override|
    override.vm.box = "parallels/ubuntu-14.04"
    override.vm.box_url = "https://vagrantcloud.com/parallels/ubuntu-14.04"
  end

  config.vm.provider "vmware_fusion" do |v, override|
    override.vm.box = "puphpet/ubuntu1404-x64"
  end


  config.vm.network "private_network", ip: "192.168.13.100"
  config.vm.hostname = "prestashop"

  config.vm.provider "virtualbox" do |v|
    v.name = "prestashop"
    v.memory = 1024
  end

  config.ssh.forward_agent = true
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.synced_folder "../", "/opt/fyndiq-prestashop-module"

  config.vm.provision :shell, path: "./provision1.6.sh"
  config.vm.provision "shell", inline: "service apache2 restart", run: "always"
end
